spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=root
spring.datasource.password=Zpqmrta_55

spring.jpa.hibernate.ddl-auto=update


openrouter.api.key=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